Repository GatorEducator/quizagator, pull requests merged in 2019-04, with the labels that each got.

#4 Refactor to pass linters
  .flake8
  .pylintrc
  application/__init__.py
  application/db_connect.py
  application/index.py
  application/login.py
  application/students.py
  application/teachers.py
Labels: enhancement

#6 Add links between student dashboard / classes, teacher dashboard / classes, and login / register pages
  application/templates/index.html
  application/templates/register.html
  application/templates/students/base_template.html
  application/templates/students/classes.html
  application/templates/students/quiz_page.html
  application/templates/teachers/base_template.html
Labels: quickfix

#9 Added updated README
  README.md
Labels: Documentation

#22 Automated docker builds
  .dockerignore
  .travis.yml
  README.md
  application/__init__.py
  application/app.py
  application/db_connect.py
  application/index.py
  application/login.py
  application/students.py
  application/teachers.py
  run.py
  scripts/create-docker-image.sh
  scripts/run-docker-image.sh
  scripts/version.sh
  tests/test_app.py
Labels: automation, patch

#23 Add Gunicorn
  .dockerignore
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  application/appfactory.py
  application/db_connect.py
  application/wsgi.py
  run.py
  scripts/create-docker-image.sh
  scripts/run-docker-image.sh
  tests/test_app.py
Labels: enhancement, patch

#25 Feature/docker database
  .dockerignore
  Dockerfile
  application/db_connect.py
  application/wsgi.py
  data/database.db
  data/quizagator.db
  run.py
  scripts/run-docker-image.sh
Labels: enhancement, minor
