Repository GatorEducator/quizagator, pull requests merged in 2019-05, with the labels that each got.

#24 Csv upload
  application/appfactory.py
  application/db_connect.py
  application/students.py
  application/teachers.py
  application/templates/teachers/class_page.html
  application/templates/teachers/classes.html
  application/templates/teachers/classes/class_page.html
  application/templates/teachers/index.html
  application/templates/teachers/quiz_page.html
  application/templates/teachers/quizzes.html
  application/templates/teachers/quizzes/create.html
  application/templates/teachers/quizzes/index.html
  data/database.db
  data/quizagator.db
Labels: minor

#29 Complete quiz presentation
  application/db_connect.py
  application/login.py
  application/students.py
  application/teachers.py
  application/templates/students/base_template.html
  application/templates/students/class_page.html
  application/templates/students/classes.html
  application/templates/students/quiz_page.html
  application/templates/teachers/base_template.html
  application/templates/teachers/classes/class_page.html
  application/templates/teachers/classes/create.html
  application/templates/teachers/index.html
  application/templates/teachers/quizzes/create.html
  application/templates/teachers/quizzes/index.html
  data/quizagator.db
Labels: enhancement, minor

#36 Quickfix/update database
  application/db_connect.py
  data/quizagator.db
Labels: patch

#38 Full release
  application/db_connect.py
  application/students.py
  application/templates/students/base_template.html
  application/templates/students/classes.html
  application/templates/students/index.html
  application/templates/students/join.html
  application/templates/students/quiz_grade.html
  application/templates/teachers/base_template.html
  application/templates/teachers/classes/class_page.html
  application/templates/teachers/index.html
  run.py
Labels: enhancement, major

#39 Read me update
  README.md
Labels: patch, quickfix

#44 Fix class grade display and invalid links
  application/db_connect.py
  application/templates/students/class_page.html
  application/templates/students/quiz_grade.html
  application/templates/teachers/classes/class_page.html
Labels: bug, patch
